services:

  postgres:
    image: postgres:17-alpine
    container_name: postgres_shortener
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d shortener" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: redis_shortener
    ports:
      - "6379:6379"

  shortener:
    build: .
    container_name: shortener_app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_MASTER_DSN=postgres://postgres:pass@postgres:5432/shortener?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    profiles:
      - app
