app:
  app_name: "shortener"
  app_version: "0.0.1"

httpserver:
  addr: ":8080"
  read_timeout: "5s"          # Время на чтение тела запроса. Защита от медленных клиентов.
  write_timeout: "10s"        # Время на запись ответа
  idle_timeout: "60s"         # Время жизни неактивного Keep-Alive соединения
  shutdown_timeout: "15s"     # Graceful Shutdown timer
  max_header_bytes: 1048576   # 1MB. Защита от Dos-атак через гигантские HTTP-заголовки.

router:
  gin_mode: debug

postgres:
  master_dsn: "postgres://postgres:pass@localhost:5432/shortener?sslmode=disable"
  slaves_dsn: []
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_life_time: 20m

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  ttl: 24h
